#!/bin/bash
#
# Module 61: Install and Configure fapolicyd
# File Access Policy Daemon for application whitelisting
# NIST 800-171 Control: 3.4.8, 3.14.2, 3.14.6
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Load installation variables
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/install_vars.sh"

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [61-FAPOLICYD] $*"
}

log "Installing fapolicyd (File Access Policy Daemon)..."

# Step 1: Install fapolicyd
log "Step 1: Installing fapolicyd packages..."
dnf install -y fapolicyd fapolicyd-selinux

log "✓ fapolicyd packages installed"

# Step 2: Configure fapolicyd
log "Step 2: Configuring fapolicyd..."

# Backup original config
cp /etc/fapolicyd/fapolicyd.conf /etc/fapolicyd/fapolicyd.conf.orig

cat > /etc/fapolicyd/fapolicyd.conf <<'EOF'
# CyberHygiene fapolicyd Configuration
# NIST 800-171 Compliant Application Whitelisting

# Start in enforcing mode (0 = enforcing, 1 = permissive)
permissive = 0

# Process priority adjustment
nice_val = 14

# Queue size for file access decisions
q_size = 800

# User and group to run as
uid = fapolicyd
gid = fapolicyd

# Enable statistics reporting
do_stat_report = 1
detailed_report = 1

# Maximum database size in megabytes
db_max_size = 50

# Cache sizes
subj_cache_size = 1549
obj_cache_size = 8191

# Filesystems to watch (add all relevant local filesystems)
watch_fs = ext2,ext3,ext4,tmpfs,xfs,vfat,iso9660,btrfs

# Trust sources: RPM database and file trust list
trust = rpmdb,file

# Integrity checking (none, hash, or size)
# Use 'none' for performance, 'hash' for stronger security
integrity = none

# Syslog format for audit trail
syslog_format = rule,dec,perm,auid,pid,exe,:,path,ftype,trust

# SHA256 only for RPM (required for FIPS compliance)
rpm_sha256_only = 0

# Filesystem marking
allow_filesystem_mark = 0

# Report interval (0 = only on change)
report_interval = 0
EOF

log "✓ fapolicyd configuration created"

# Step 3: Create initial trust file
log "Step 3: Creating initial trust file..."

cat > /etc/fapolicyd/fapolicyd.trust <<'EOF'
# CyberHygiene fapolicyd Trust File
# AUTOGENERATED FILE VERSION 3
# This file contains a list of trusted files not in RPM database
#
#  FULL PATH        SIZE                             SHA256
EOF

log "✓ Trust file created"

# Step 4: Add custom rules for CyberHygiene services
log "Step 4: Adding trust entries for CyberHygiene services..."

# Function to add trust entry
add_trust() {
    local filepath="$1"
    if [[ -f "${filepath}" ]]; then
        local size=$(stat -c%s "${filepath}")
        local hash=$(sha256sum "${filepath}" | awk '{print $1}')
        echo "${filepath} ${size} ${hash}" >> /etc/fapolicyd/fapolicyd.trust
        log "  Added: ${filepath}"
    else
        log "  Skipped (not found): ${filepath}"
    fi
}

# Add container-related binaries (podman, crun)
add_trust /usr/bin/crun
add_trust /usr/bin/podman
add_trust /usr/bin/conmon

# Wazuh Dashboard node binaries (critical for Wazuh to start)
if [[ -d /usr/share/wazuh-dashboard/node ]]; then
    add_trust /usr/share/wazuh-dashboard/node/bin/node
    add_trust /usr/share/wazuh-dashboard/node/fallback/bin/node
fi

# Any custom scripts or binaries
# Add additional entries as needed during deployment

log "✓ Trust entries added"

# Step 5: Configure SELinux for fapolicyd
log "Step 5: Configuring SELinux for fapolicyd..."

# Set proper SELinux context for Wazuh node binaries
if [[ -d /usr/share/wazuh-dashboard/node ]]; then
    semanage fcontext -a -t bin_t "/usr/share/wazuh-dashboard/node(/.*)?/bin/node" 2>/dev/null || \
    semanage fcontext -m -t bin_t "/usr/share/wazuh-dashboard/node(/.*)?/bin/node" 2>/dev/null || true
    restorecon -Rv /usr/share/wazuh-dashboard/node/ 2>/dev/null || true
    log "✓ SELinux context configured for Wazuh node binaries"
fi

# Step 6: Enable and start fapolicyd
log "Step 6: Enabling and starting fapolicyd..."

# Update the trust database
fapolicyd-cli --update 2>/dev/null || true

systemctl daemon-reload
systemctl enable fapolicyd
systemctl start fapolicyd

sleep 3

if systemctl is-active --quiet fapolicyd; then
    log "✓ fapolicyd is running"
else
    log "WARNING: fapolicyd failed to start"
    log "Check logs: journalctl -u fapolicyd"
    # Don't exit - fapolicyd issues shouldn't block installation
fi

# Step 7: Verify fapolicyd rules
log "Step 7: Verifying fapolicyd rules..."
fapolicyd-cli --list | head -20
log "✓ Rules loaded"

# Summary
echo ""
log "=========================================="
log "fapolicyd Installation Summary"
log "=========================================="
log "✓ fapolicyd installed and configured"
log "✓ Application whitelisting enabled"
log "✓ Trust database initialized"
log ""
log "Configuration: /etc/fapolicyd/fapolicyd.conf"
log "Trust file: /etc/fapolicyd/fapolicyd.trust"
log "Rules: /etc/fapolicyd/rules.d/"
log ""
log "Management commands:"
log "  fapolicyd-cli --list              # List rules"
log "  fapolicyd-cli --dump-db           # Show trust database"
log "  fapolicyd-cli --update            # Update database"
log "  fapolicyd-cli --file add <path>   # Add file to trust"
log ""
log "To add new trusted files:"
log "  fapolicyd-cli --file add /path/to/file"
log "  fapolicyd-cli --update"
log ""

exit 0
