#!/bin/bash
#
# Module 11: Configure DNS Settings
# Additional DNS configuration and verification
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Load installation variables
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/install_vars.sh"

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [11-DNS] $*"
}

log "Configuring DNS settings..."

# Authenticate to FreeIPA
log "Authenticating to FreeIPA..."
if ! echo "${ADMIN_PASSWORD}" | kinit admin 2>/dev/null; then
    log "ERROR: Failed to authenticate to FreeIPA"
    exit 1
fi

# Configure DNS to use itself as resolver
log "Configuring system to use local DNS..."
cat > /etc/resolv.conf <<EOF
# Generated by CyberHygiene installer
# Local FreeIPA DNS server
nameserver ${DC1_IP}
search ${DOMAIN}
EOF

# Make resolv.conf immutable (prevent NetworkManager from overwriting)
chattr +i /etc/resolv.conf 2>/dev/null || true

log "✓ System DNS configured"

# Create DNS service records
log "Creating DNS service records..."

# LDAP service records
ipa dnsrecord-add "${DOMAIN}." _ldap._tcp --srv-priority=0 --srv-weight=100 --srv-port=389 --srv-target="${DC1_HOSTNAME}." 2>/dev/null || true
ipa dnsrecord-add "${DOMAIN}." _ldaps._tcp --srv-priority=0 --srv-weight=100 --srv-port=636 --srv-target="${DC1_HOSTNAME}." 2>/dev/null || true

# Kerberos service records
ipa dnsrecord-add "${DOMAIN}." _kerberos._tcp --srv-priority=0 --srv-weight=100 --srv-port=88 --srv-target="${DC1_HOSTNAME}." 2>/dev/null || true
ipa dnsrecord-add "${DOMAIN}." _kerberos._udp --srv-priority=0 --srv-weight=100 --srv-port=88 --srv-target="${DC1_HOSTNAME}." 2>/dev/null || true
ipa dnsrecord-add "${DOMAIN}." _kpasswd._tcp --srv-priority=0 --srv-weight=100 --srv-port=464 --srv-target="${DC1_HOSTNAME}." 2>/dev/null || true
ipa dnsrecord-add "${DOMAIN}." _kpasswd._udp --srv-priority=0 --srv-weight=100 --srv-port=464 --srv-target="${DC1_HOSTNAME}." 2>/dev/null || true

log "✓ Service records created"

# Create CNAME records for common services
log "Creating CNAME records for services..."
ipa dnsrecord-add "${DOMAIN}." cpm --cname-hostname="${DC1_HOSTNAME}." 2>/dev/null || true
ipa dnsrecord-add "${DOMAIN}." grafana --cname-hostname=monitoring."${DOMAIN}." 2>/dev/null || true

log "✓ CNAME records created"

# Test DNS resolution
log "Testing DNS resolution..."
TESTS_PASSED=0
TESTS_FAILED=0

for hostname in "dc1" "dms" "graylog" "proxy" "monitoring" "wazuh"; do
    if host "${hostname}.${DOMAIN}" ${DC1_IP} &>/dev/null; then
        log "  ✓ ${hostname}.${DOMAIN} resolves"
        ((TESTS_PASSED++))
    else
        log "  ✗ ${hostname}.${DOMAIN} failed to resolve"
        ((TESTS_FAILED++))
    fi
done

log "DNS tests: ${TESTS_PASSED} passed, ${TESTS_FAILED} failed"

kdestroy

echo ""
log "=========================================="
log "DNS Configuration Summary"
log "=========================================="
log "✓ DNS server: ${DC1_IP}"
log "✓ Domain: ${DOMAIN}"
log "✓ Service records created"
log "✓ CNAME records created"
log "✓ System configured to use local DNS"
log ""

exit 0
